### PR TITLE
dependency update to babel 6

### PR DESCRIPTION
**Pull request by BeneStem**

### CODE REVIEW

**Comment by shuhei** [comment]
Thanks! Would you mind squashing the two commits into one?

**Comment by BeneStem** [comment]
sure. no problem.
didnt saw that until now :-/
sorry!

**Comment by BeneStem** [comment]
done.

**Comment by shuhei** [comment]
Thanks!

**Comment by BeneStem** [comment]
no problem! would you be so kind and release it to npm.
then i could switch back from my fork to your repo.

**Comment by shuhei** [comment]
Before releasing it, I'm going to update the README to tell people that they have to install a preset like `babel-preset-es2015`.

**Comment by BeneStem** [comment]
good idea.
ill be patient ;)

**Comment by shuhei** [comment]
Published :-)

**Comment by BeneStem** [comment]
Much appreciated :)

**Pull request merged**
